/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated.app.onboarding'
import { Route as AuthenticatedAppTasksIndexRouteImport } from './routes/_authenticated.app.tasks.index'
import { Route as AuthenticatedAppSuppliersIndexRouteImport } from './routes/_authenticated.app.suppliers.index'
import { Route as AuthenticatedAppStaffIndexRouteImport } from './routes/_authenticated.app.staff.index'
import { Route as AuthenticatedAppSettingsIndexRouteImport } from './routes/_authenticated.app.settings.index'
import { Route as AuthenticatedAppReportsIndexRouteImport } from './routes/_authenticated.app.reports.index'
import { Route as AuthenticatedAppQuotationsIndexRouteImport } from './routes/_authenticated.app.quotations.index'
import { Route as AuthenticatedAppPurchaseOrdersIndexRouteImport } from './routes/_authenticated.app.purchase-orders.index'
import { Route as AuthenticatedAppNotificationsIndexRouteImport } from './routes/_authenticated.app.notifications.index'
import { Route as AuthenticatedAppInvoicesIndexRouteImport } from './routes/_authenticated.app.invoices.index'
import { Route as AuthenticatedAppInventoryIndexRouteImport } from './routes/_authenticated.app.inventory.index'
import { Route as AuthenticatedAppFollowUpsIndexRouteImport } from './routes/_authenticated.app.follow-ups.index'
import { Route as AuthenticatedAppEventsIndexRouteImport } from './routes/_authenticated.app.events.index'
import { Route as AuthenticatedAppCustomersIndexRouteImport } from './routes/_authenticated.app.customers.index'
import { Route as AuthenticatedAppCalendarIndexRouteImport } from './routes/_authenticated.app.calendar.index'
import { Route as AuthenticatedAppAuditLogIndexRouteImport } from './routes/_authenticated.app.audit-log.index'
import { Route as AuthenticatedAppPurchaseOrdersNewRouteImport } from './routes/_authenticated.app.purchase-orders.new'
import { Route as AuthenticatedAppPurchaseOrdersIdRouteImport } from './routes/_authenticated.app.purchase-orders.$id'
import { Route as AuthenticatedAppInvoicesNewRouteImport } from './routes/_authenticated.app.invoices.new'
import { Route as AuthenticatedAppInvoicesIdRouteImport } from './routes/_authenticated.app.invoices.$id'
import { Route as AuthenticatedAppInventoryNewRouteImport } from './routes/_authenticated.app.inventory.new'
import { Route as AuthenticatedAppInventoryIdRouteImport } from './routes/_authenticated.app.inventory.$id'
import { Route as AuthenticatedAppEventsNewRouteImport } from './routes/_authenticated.app.events.new'
import { Route as AuthenticatedAppEventsIdRouteImport } from './routes/_authenticated.app.events.$id'
import { Route as AuthenticatedAppCustomersNewRouteImport } from './routes/_authenticated.app.customers.new'
import { Route as AuthenticatedAppCustomersIdRouteImport } from './routes/_authenticated.app.customers.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTasksIndexRoute =
  AuthenticatedAppTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSuppliersIndexRoute =
  AuthenticatedAppSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppStaffIndexRoute =
  AuthenticatedAppStaffIndexRouteImport.update({
    id: '/staff/',
    path: '/staff/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReportsIndexRoute =
  AuthenticatedAppReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppQuotationsIndexRoute =
  AuthenticatedAppQuotationsIndexRouteImport.update({
    id: '/quotations/',
    path: '/quotations/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPurchaseOrdersIndexRoute =
  AuthenticatedAppPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNotificationsIndexRoute =
  AuthenticatedAppNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInvoicesIndexRoute =
  AuthenticatedAppInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInventoryIndexRoute =
  AuthenticatedAppInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFollowUpsIndexRoute =
  AuthenticatedAppFollowUpsIndexRouteImport.update({
    id: '/follow-ups/',
    path: '/follow-ups/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEventsIndexRoute =
  AuthenticatedAppEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCustomersIndexRoute =
  AuthenticatedAppCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCalendarIndexRoute =
  AuthenticatedAppCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAuditLogIndexRoute =
  AuthenticatedAppAuditLogIndexRouteImport.update({
    id: '/audit-log/',
    path: '/audit-log/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPurchaseOrdersNewRoute =
  AuthenticatedAppPurchaseOrdersNewRouteImport.update({
    id: '/purchase-orders/new',
    path: '/purchase-orders/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPurchaseOrdersIdRoute =
  AuthenticatedAppPurchaseOrdersIdRouteImport.update({
    id: '/purchase-orders/$id',
    path: '/purchase-orders/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInvoicesNewRoute =
  AuthenticatedAppInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInvoicesIdRoute =
  AuthenticatedAppInvoicesIdRouteImport.update({
    id: '/invoices/$id',
    path: '/invoices/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInventoryNewRoute =
  AuthenticatedAppInventoryNewRouteImport.update({
    id: '/inventory/new',
    path: '/inventory/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInventoryIdRoute =
  AuthenticatedAppInventoryIdRouteImport.update({
    id: '/inventory/$id',
    path: '/inventory/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEventsNewRoute =
  AuthenticatedAppEventsNewRouteImport.update({
    id: '/events/new',
    path: '/events/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEventsIdRoute =
  AuthenticatedAppEventsIdRouteImport.update({
    id: '/events/$id',
    path: '/events/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCustomersNewRoute =
  AuthenticatedAppCustomersNewRouteImport.update({
    id: '/customers/new',
    path: '/customers/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCustomersIdRoute =
  AuthenticatedAppCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/customers/$id': typeof AuthenticatedAppCustomersIdRoute
  '/app/customers/new': typeof AuthenticatedAppCustomersNewRoute
  '/app/events/$id': typeof AuthenticatedAppEventsIdRoute
  '/app/events/new': typeof AuthenticatedAppEventsNewRoute
  '/app/inventory/$id': typeof AuthenticatedAppInventoryIdRoute
  '/app/inventory/new': typeof AuthenticatedAppInventoryNewRoute
  '/app/invoices/$id': typeof AuthenticatedAppInvoicesIdRoute
  '/app/invoices/new': typeof AuthenticatedAppInvoicesNewRoute
  '/app/purchase-orders/$id': typeof AuthenticatedAppPurchaseOrdersIdRoute
  '/app/purchase-orders/new': typeof AuthenticatedAppPurchaseOrdersNewRoute
  '/app/audit-log/': typeof AuthenticatedAppAuditLogIndexRoute
  '/app/calendar/': typeof AuthenticatedAppCalendarIndexRoute
  '/app/customers/': typeof AuthenticatedAppCustomersIndexRoute
  '/app/events/': typeof AuthenticatedAppEventsIndexRoute
  '/app/follow-ups/': typeof AuthenticatedAppFollowUpsIndexRoute
  '/app/inventory/': typeof AuthenticatedAppInventoryIndexRoute
  '/app/invoices/': typeof AuthenticatedAppInvoicesIndexRoute
  '/app/notifications/': typeof AuthenticatedAppNotificationsIndexRoute
  '/app/purchase-orders/': typeof AuthenticatedAppPurchaseOrdersIndexRoute
  '/app/quotations/': typeof AuthenticatedAppQuotationsIndexRoute
  '/app/reports/': typeof AuthenticatedAppReportsIndexRoute
  '/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/app/staff/': typeof AuthenticatedAppStaffIndexRoute
  '/app/suppliers/': typeof AuthenticatedAppSuppliersIndexRoute
  '/app/tasks/': typeof AuthenticatedAppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/customers/$id': typeof AuthenticatedAppCustomersIdRoute
  '/app/customers/new': typeof AuthenticatedAppCustomersNewRoute
  '/app/events/$id': typeof AuthenticatedAppEventsIdRoute
  '/app/events/new': typeof AuthenticatedAppEventsNewRoute
  '/app/inventory/$id': typeof AuthenticatedAppInventoryIdRoute
  '/app/inventory/new': typeof AuthenticatedAppInventoryNewRoute
  '/app/invoices/$id': typeof AuthenticatedAppInvoicesIdRoute
  '/app/invoices/new': typeof AuthenticatedAppInvoicesNewRoute
  '/app/purchase-orders/$id': typeof AuthenticatedAppPurchaseOrdersIdRoute
  '/app/purchase-orders/new': typeof AuthenticatedAppPurchaseOrdersNewRoute
  '/app/audit-log': typeof AuthenticatedAppAuditLogIndexRoute
  '/app/calendar': typeof AuthenticatedAppCalendarIndexRoute
  '/app/customers': typeof AuthenticatedAppCustomersIndexRoute
  '/app/events': typeof AuthenticatedAppEventsIndexRoute
  '/app/follow-ups': typeof AuthenticatedAppFollowUpsIndexRoute
  '/app/inventory': typeof AuthenticatedAppInventoryIndexRoute
  '/app/invoices': typeof AuthenticatedAppInvoicesIndexRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsIndexRoute
  '/app/purchase-orders': typeof AuthenticatedAppPurchaseOrdersIndexRoute
  '/app/quotations': typeof AuthenticatedAppQuotationsIndexRoute
  '/app/reports': typeof AuthenticatedAppReportsIndexRoute
  '/app/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/app/staff': typeof AuthenticatedAppStaffIndexRoute
  '/app/suppliers': typeof AuthenticatedAppSuppliersIndexRoute
  '/app/tasks': typeof AuthenticatedAppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/customers/$id': typeof AuthenticatedAppCustomersIdRoute
  '/_authenticated/app/customers/new': typeof AuthenticatedAppCustomersNewRoute
  '/_authenticated/app/events/$id': typeof AuthenticatedAppEventsIdRoute
  '/_authenticated/app/events/new': typeof AuthenticatedAppEventsNewRoute
  '/_authenticated/app/inventory/$id': typeof AuthenticatedAppInventoryIdRoute
  '/_authenticated/app/inventory/new': typeof AuthenticatedAppInventoryNewRoute
  '/_authenticated/app/invoices/$id': typeof AuthenticatedAppInvoicesIdRoute
  '/_authenticated/app/invoices/new': typeof AuthenticatedAppInvoicesNewRoute
  '/_authenticated/app/purchase-orders/$id': typeof AuthenticatedAppPurchaseOrdersIdRoute
  '/_authenticated/app/purchase-orders/new': typeof AuthenticatedAppPurchaseOrdersNewRoute
  '/_authenticated/app/audit-log/': typeof AuthenticatedAppAuditLogIndexRoute
  '/_authenticated/app/calendar/': typeof AuthenticatedAppCalendarIndexRoute
  '/_authenticated/app/customers/': typeof AuthenticatedAppCustomersIndexRoute
  '/_authenticated/app/events/': typeof AuthenticatedAppEventsIndexRoute
  '/_authenticated/app/follow-ups/': typeof AuthenticatedAppFollowUpsIndexRoute
  '/_authenticated/app/inventory/': typeof AuthenticatedAppInventoryIndexRoute
  '/_authenticated/app/invoices/': typeof AuthenticatedAppInvoicesIndexRoute
  '/_authenticated/app/notifications/': typeof AuthenticatedAppNotificationsIndexRoute
  '/_authenticated/app/purchase-orders/': typeof AuthenticatedAppPurchaseOrdersIndexRoute
  '/_authenticated/app/quotations/': typeof AuthenticatedAppQuotationsIndexRoute
  '/_authenticated/app/reports/': typeof AuthenticatedAppReportsIndexRoute
  '/_authenticated/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/_authenticated/app/staff/': typeof AuthenticatedAppStaffIndexRoute
  '/_authenticated/app/suppliers/': typeof AuthenticatedAppSuppliersIndexRoute
  '/_authenticated/app/tasks/': typeof AuthenticatedAppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app'
    | '/app/onboarding'
    | '/app/'
    | '/app/customers/$id'
    | '/app/customers/new'
    | '/app/events/$id'
    | '/app/events/new'
    | '/app/inventory/$id'
    | '/app/inventory/new'
    | '/app/invoices/$id'
    | '/app/invoices/new'
    | '/app/purchase-orders/$id'
    | '/app/purchase-orders/new'
    | '/app/audit-log/'
    | '/app/calendar/'
    | '/app/customers/'
    | '/app/events/'
    | '/app/follow-ups/'
    | '/app/inventory/'
    | '/app/invoices/'
    | '/app/notifications/'
    | '/app/purchase-orders/'
    | '/app/quotations/'
    | '/app/reports/'
    | '/app/settings/'
    | '/app/staff/'
    | '/app/suppliers/'
    | '/app/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/onboarding'
    | '/app'
    | '/app/customers/$id'
    | '/app/customers/new'
    | '/app/events/$id'
    | '/app/events/new'
    | '/app/inventory/$id'
    | '/app/inventory/new'
    | '/app/invoices/$id'
    | '/app/invoices/new'
    | '/app/purchase-orders/$id'
    | '/app/purchase-orders/new'
    | '/app/audit-log'
    | '/app/calendar'
    | '/app/customers'
    | '/app/events'
    | '/app/follow-ups'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/notifications'
    | '/app/purchase-orders'
    | '/app/quotations'
    | '/app/reports'
    | '/app/settings'
    | '/app/staff'
    | '/app/suppliers'
    | '/app/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/app'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/'
    | '/_authenticated/app/customers/$id'
    | '/_authenticated/app/customers/new'
    | '/_authenticated/app/events/$id'
    | '/_authenticated/app/events/new'
    | '/_authenticated/app/inventory/$id'
    | '/_authenticated/app/inventory/new'
    | '/_authenticated/app/invoices/$id'
    | '/_authenticated/app/invoices/new'
    | '/_authenticated/app/purchase-orders/$id'
    | '/_authenticated/app/purchase-orders/new'
    | '/_authenticated/app/audit-log/'
    | '/_authenticated/app/calendar/'
    | '/_authenticated/app/customers/'
    | '/_authenticated/app/events/'
    | '/_authenticated/app/follow-ups/'
    | '/_authenticated/app/inventory/'
    | '/_authenticated/app/invoices/'
    | '/_authenticated/app/notifications/'
    | '/_authenticated/app/purchase-orders/'
    | '/_authenticated/app/quotations/'
    | '/_authenticated/app/reports/'
    | '/_authenticated/app/settings/'
    | '/_authenticated/app/staff/'
    | '/_authenticated/app/suppliers/'
    | '/_authenticated/app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tasks/': {
      id: '/_authenticated/app/tasks/'
      path: '/tasks'
      fullPath: '/app/tasks/'
      preLoaderRoute: typeof AuthenticatedAppTasksIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/suppliers/': {
      id: '/_authenticated/app/suppliers/'
      path: '/suppliers'
      fullPath: '/app/suppliers/'
      preLoaderRoute: typeof AuthenticatedAppSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/staff/': {
      id: '/_authenticated/app/staff/'
      path: '/staff'
      fullPath: '/app/staff/'
      preLoaderRoute: typeof AuthenticatedAppStaffIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/': {
      id: '/_authenticated/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reports/': {
      id: '/_authenticated/app/reports/'
      path: '/reports'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AuthenticatedAppReportsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/quotations/': {
      id: '/_authenticated/app/quotations/'
      path: '/quotations'
      fullPath: '/app/quotations/'
      preLoaderRoute: typeof AuthenticatedAppQuotationsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/purchase-orders/': {
      id: '/_authenticated/app/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders/'
      preLoaderRoute: typeof AuthenticatedAppPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications/': {
      id: '/_authenticated/app/notifications/'
      path: '/notifications'
      fullPath: '/app/notifications/'
      preLoaderRoute: typeof AuthenticatedAppNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/invoices/': {
      id: '/_authenticated/app/invoices/'
      path: '/invoices'
      fullPath: '/app/invoices/'
      preLoaderRoute: typeof AuthenticatedAppInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inventory/': {
      id: '/_authenticated/app/inventory/'
      path: '/inventory'
      fullPath: '/app/inventory/'
      preLoaderRoute: typeof AuthenticatedAppInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/follow-ups/': {
      id: '/_authenticated/app/follow-ups/'
      path: '/follow-ups'
      fullPath: '/app/follow-ups/'
      preLoaderRoute: typeof AuthenticatedAppFollowUpsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/events/': {
      id: '/_authenticated/app/events/'
      path: '/events'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AuthenticatedAppEventsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/customers/': {
      id: '/_authenticated/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AuthenticatedAppCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/calendar/': {
      id: '/_authenticated/app/calendar/'
      path: '/calendar'
      fullPath: '/app/calendar/'
      preLoaderRoute: typeof AuthenticatedAppCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/audit-log/': {
      id: '/_authenticated/app/audit-log/'
      path: '/audit-log'
      fullPath: '/app/audit-log/'
      preLoaderRoute: typeof AuthenticatedAppAuditLogIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/purchase-orders/new': {
      id: '/_authenticated/app/purchase-orders/new'
      path: '/purchase-orders/new'
      fullPath: '/app/purchase-orders/new'
      preLoaderRoute: typeof AuthenticatedAppPurchaseOrdersNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/purchase-orders/$id': {
      id: '/_authenticated/app/purchase-orders/$id'
      path: '/purchase-orders/$id'
      fullPath: '/app/purchase-orders/$id'
      preLoaderRoute: typeof AuthenticatedAppPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/invoices/new': {
      id: '/_authenticated/app/invoices/new'
      path: '/invoices/new'
      fullPath: '/app/invoices/new'
      preLoaderRoute: typeof AuthenticatedAppInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/invoices/$id': {
      id: '/_authenticated/app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/app/invoices/$id'
      preLoaderRoute: typeof AuthenticatedAppInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inventory/new': {
      id: '/_authenticated/app/inventory/new'
      path: '/inventory/new'
      fullPath: '/app/inventory/new'
      preLoaderRoute: typeof AuthenticatedAppInventoryNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inventory/$id': {
      id: '/_authenticated/app/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/app/inventory/$id'
      preLoaderRoute: typeof AuthenticatedAppInventoryIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/events/new': {
      id: '/_authenticated/app/events/new'
      path: '/events/new'
      fullPath: '/app/events/new'
      preLoaderRoute: typeof AuthenticatedAppEventsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/events/$id': {
      id: '/_authenticated/app/events/$id'
      path: '/events/$id'
      fullPath: '/app/events/$id'
      preLoaderRoute: typeof AuthenticatedAppEventsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/customers/new': {
      id: '/_authenticated/app/customers/new'
      path: '/customers/new'
      fullPath: '/app/customers/new'
      preLoaderRoute: typeof AuthenticatedAppCustomersNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/customers/$id': {
      id: '/_authenticated/app/customers/$id'
      path: '/customers/$id'
      fullPath: '/app/customers/$id'
      preLoaderRoute: typeof AuthenticatedAppCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCustomersIdRoute: typeof AuthenticatedAppCustomersIdRoute
  AuthenticatedAppCustomersNewRoute: typeof AuthenticatedAppCustomersNewRoute
  AuthenticatedAppEventsIdRoute: typeof AuthenticatedAppEventsIdRoute
  AuthenticatedAppEventsNewRoute: typeof AuthenticatedAppEventsNewRoute
  AuthenticatedAppInventoryIdRoute: typeof AuthenticatedAppInventoryIdRoute
  AuthenticatedAppInventoryNewRoute: typeof AuthenticatedAppInventoryNewRoute
  AuthenticatedAppInvoicesIdRoute: typeof AuthenticatedAppInvoicesIdRoute
  AuthenticatedAppInvoicesNewRoute: typeof AuthenticatedAppInvoicesNewRoute
  AuthenticatedAppPurchaseOrdersIdRoute: typeof AuthenticatedAppPurchaseOrdersIdRoute
  AuthenticatedAppPurchaseOrdersNewRoute: typeof AuthenticatedAppPurchaseOrdersNewRoute
  AuthenticatedAppAuditLogIndexRoute: typeof AuthenticatedAppAuditLogIndexRoute
  AuthenticatedAppCalendarIndexRoute: typeof AuthenticatedAppCalendarIndexRoute
  AuthenticatedAppCustomersIndexRoute: typeof AuthenticatedAppCustomersIndexRoute
  AuthenticatedAppEventsIndexRoute: typeof AuthenticatedAppEventsIndexRoute
  AuthenticatedAppFollowUpsIndexRoute: typeof AuthenticatedAppFollowUpsIndexRoute
  AuthenticatedAppInventoryIndexRoute: typeof AuthenticatedAppInventoryIndexRoute
  AuthenticatedAppInvoicesIndexRoute: typeof AuthenticatedAppInvoicesIndexRoute
  AuthenticatedAppNotificationsIndexRoute: typeof AuthenticatedAppNotificationsIndexRoute
  AuthenticatedAppPurchaseOrdersIndexRoute: typeof AuthenticatedAppPurchaseOrdersIndexRoute
  AuthenticatedAppQuotationsIndexRoute: typeof AuthenticatedAppQuotationsIndexRoute
  AuthenticatedAppReportsIndexRoute: typeof AuthenticatedAppReportsIndexRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
  AuthenticatedAppStaffIndexRoute: typeof AuthenticatedAppStaffIndexRoute
  AuthenticatedAppSuppliersIndexRoute: typeof AuthenticatedAppSuppliersIndexRoute
  AuthenticatedAppTasksIndexRoute: typeof AuthenticatedAppTasksIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCustomersIdRoute: AuthenticatedAppCustomersIdRoute,
  AuthenticatedAppCustomersNewRoute: AuthenticatedAppCustomersNewRoute,
  AuthenticatedAppEventsIdRoute: AuthenticatedAppEventsIdRoute,
  AuthenticatedAppEventsNewRoute: AuthenticatedAppEventsNewRoute,
  AuthenticatedAppInventoryIdRoute: AuthenticatedAppInventoryIdRoute,
  AuthenticatedAppInventoryNewRoute: AuthenticatedAppInventoryNewRoute,
  AuthenticatedAppInvoicesIdRoute: AuthenticatedAppInvoicesIdRoute,
  AuthenticatedAppInvoicesNewRoute: AuthenticatedAppInvoicesNewRoute,
  AuthenticatedAppPurchaseOrdersIdRoute: AuthenticatedAppPurchaseOrdersIdRoute,
  AuthenticatedAppPurchaseOrdersNewRoute:
    AuthenticatedAppPurchaseOrdersNewRoute,
  AuthenticatedAppAuditLogIndexRoute: AuthenticatedAppAuditLogIndexRoute,
  AuthenticatedAppCalendarIndexRoute: AuthenticatedAppCalendarIndexRoute,
  AuthenticatedAppCustomersIndexRoute: AuthenticatedAppCustomersIndexRoute,
  AuthenticatedAppEventsIndexRoute: AuthenticatedAppEventsIndexRoute,
  AuthenticatedAppFollowUpsIndexRoute: AuthenticatedAppFollowUpsIndexRoute,
  AuthenticatedAppInventoryIndexRoute: AuthenticatedAppInventoryIndexRoute,
  AuthenticatedAppInvoicesIndexRoute: AuthenticatedAppInvoicesIndexRoute,
  AuthenticatedAppNotificationsIndexRoute:
    AuthenticatedAppNotificationsIndexRoute,
  AuthenticatedAppPurchaseOrdersIndexRoute:
    AuthenticatedAppPurchaseOrdersIndexRoute,
  AuthenticatedAppQuotationsIndexRoute: AuthenticatedAppQuotationsIndexRoute,
  AuthenticatedAppReportsIndexRoute: AuthenticatedAppReportsIndexRoute,
  AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
  AuthenticatedAppStaffIndexRoute: AuthenticatedAppStaffIndexRoute,
  AuthenticatedAppSuppliersIndexRoute: AuthenticatedAppSuppliersIndexRoute,
  AuthenticatedAppTasksIndexRoute: AuthenticatedAppTasksIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
