/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated.app.onboarding'
import { Route as AuthenticatedAppSettingsIndexRouteImport } from './routes/_authenticated.app.settings.index'
import { Route as AuthenticatedAppQuotationsIndexRouteImport } from './routes/_authenticated.app.quotations.index'
import { Route as AuthenticatedAppInventoryIndexRouteImport } from './routes/_authenticated.app.inventory.index'
import { Route as AuthenticatedAppFollowUpsIndexRouteImport } from './routes/_authenticated.app.follow-ups.index'
import { Route as AuthenticatedAppEventsIndexRouteImport } from './routes/_authenticated.app.events.index'
import { Route as AuthenticatedAppCustomersIndexRouteImport } from './routes/_authenticated.app.customers.index'
import { Route as AuthenticatedAppInventoryNewRouteImport } from './routes/_authenticated.app.inventory.new'
import { Route as AuthenticatedAppInventoryIdRouteImport } from './routes/_authenticated.app.inventory.$id'
import { Route as AuthenticatedAppEventsNewRouteImport } from './routes/_authenticated.app.events.new'
import { Route as AuthenticatedAppEventsIdRouteImport } from './routes/_authenticated.app.events.$id'
import { Route as AuthenticatedAppCustomersNewRouteImport } from './routes/_authenticated.app.customers.new'
import { Route as AuthenticatedAppCustomersIdRouteImport } from './routes/_authenticated.app.customers.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_authenticated/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppQuotationsIndexRoute =
  AuthenticatedAppQuotationsIndexRouteImport.update({
    id: '/quotations/',
    path: '/quotations/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInventoryIndexRoute =
  AuthenticatedAppInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFollowUpsIndexRoute =
  AuthenticatedAppFollowUpsIndexRouteImport.update({
    id: '/follow-ups/',
    path: '/follow-ups/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEventsIndexRoute =
  AuthenticatedAppEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCustomersIndexRoute =
  AuthenticatedAppCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInventoryNewRoute =
  AuthenticatedAppInventoryNewRouteImport.update({
    id: '/inventory/new',
    path: '/inventory/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInventoryIdRoute =
  AuthenticatedAppInventoryIdRouteImport.update({
    id: '/inventory/$id',
    path: '/inventory/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEventsNewRoute =
  AuthenticatedAppEventsNewRouteImport.update({
    id: '/events/new',
    path: '/events/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEventsIdRoute =
  AuthenticatedAppEventsIdRouteImport.update({
    id: '/events/$id',
    path: '/events/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCustomersNewRoute =
  AuthenticatedAppCustomersNewRouteImport.update({
    id: '/customers/new',
    path: '/customers/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCustomersIdRoute =
  AuthenticatedAppCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/customers/$id': typeof AuthenticatedAppCustomersIdRoute
  '/app/customers/new': typeof AuthenticatedAppCustomersNewRoute
  '/app/events/$id': typeof AuthenticatedAppEventsIdRoute
  '/app/events/new': typeof AuthenticatedAppEventsNewRoute
  '/app/inventory/$id': typeof AuthenticatedAppInventoryIdRoute
  '/app/inventory/new': typeof AuthenticatedAppInventoryNewRoute
  '/app/customers/': typeof AuthenticatedAppCustomersIndexRoute
  '/app/events/': typeof AuthenticatedAppEventsIndexRoute
  '/app/follow-ups/': typeof AuthenticatedAppFollowUpsIndexRoute
  '/app/inventory/': typeof AuthenticatedAppInventoryIndexRoute
  '/app/quotations/': typeof AuthenticatedAppQuotationsIndexRoute
  '/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/customers/$id': typeof AuthenticatedAppCustomersIdRoute
  '/app/customers/new': typeof AuthenticatedAppCustomersNewRoute
  '/app/events/$id': typeof AuthenticatedAppEventsIdRoute
  '/app/events/new': typeof AuthenticatedAppEventsNewRoute
  '/app/inventory/$id': typeof AuthenticatedAppInventoryIdRoute
  '/app/inventory/new': typeof AuthenticatedAppInventoryNewRoute
  '/app/customers': typeof AuthenticatedAppCustomersIndexRoute
  '/app/events': typeof AuthenticatedAppEventsIndexRoute
  '/app/follow-ups': typeof AuthenticatedAppFollowUpsIndexRoute
  '/app/inventory': typeof AuthenticatedAppInventoryIndexRoute
  '/app/quotations': typeof AuthenticatedAppQuotationsIndexRoute
  '/app/settings': typeof AuthenticatedAppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/customers/$id': typeof AuthenticatedAppCustomersIdRoute
  '/_authenticated/app/customers/new': typeof AuthenticatedAppCustomersNewRoute
  '/_authenticated/app/events/$id': typeof AuthenticatedAppEventsIdRoute
  '/_authenticated/app/events/new': typeof AuthenticatedAppEventsNewRoute
  '/_authenticated/app/inventory/$id': typeof AuthenticatedAppInventoryIdRoute
  '/_authenticated/app/inventory/new': typeof AuthenticatedAppInventoryNewRoute
  '/_authenticated/app/customers/': typeof AuthenticatedAppCustomersIndexRoute
  '/_authenticated/app/events/': typeof AuthenticatedAppEventsIndexRoute
  '/_authenticated/app/follow-ups/': typeof AuthenticatedAppFollowUpsIndexRoute
  '/_authenticated/app/inventory/': typeof AuthenticatedAppInventoryIndexRoute
  '/_authenticated/app/quotations/': typeof AuthenticatedAppQuotationsIndexRoute
  '/_authenticated/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/app'
    | '/app/onboarding'
    | '/app/'
    | '/app/customers/$id'
    | '/app/customers/new'
    | '/app/events/$id'
    | '/app/events/new'
    | '/app/inventory/$id'
    | '/app/inventory/new'
    | '/app/customers/'
    | '/app/events/'
    | '/app/follow-ups/'
    | '/app/inventory/'
    | '/app/quotations/'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/onboarding'
    | '/app'
    | '/app/customers/$id'
    | '/app/customers/new'
    | '/app/events/$id'
    | '/app/events/new'
    | '/app/inventory/$id'
    | '/app/inventory/new'
    | '/app/customers'
    | '/app/events'
    | '/app/follow-ups'
    | '/app/inventory'
    | '/app/quotations'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/_authenticated/app'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/'
    | '/_authenticated/app/customers/$id'
    | '/_authenticated/app/customers/new'
    | '/_authenticated/app/events/$id'
    | '/_authenticated/app/events/new'
    | '/_authenticated/app/inventory/$id'
    | '/_authenticated/app/inventory/new'
    | '/_authenticated/app/customers/'
    | '/_authenticated/app/events/'
    | '/_authenticated/app/follow-ups/'
    | '/_authenticated/app/inventory/'
    | '/_authenticated/app/quotations/'
    | '/_authenticated/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/': {
      id: '/_authenticated/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/quotations/': {
      id: '/_authenticated/app/quotations/'
      path: '/quotations'
      fullPath: '/app/quotations/'
      preLoaderRoute: typeof AuthenticatedAppQuotationsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inventory/': {
      id: '/_authenticated/app/inventory/'
      path: '/inventory'
      fullPath: '/app/inventory/'
      preLoaderRoute: typeof AuthenticatedAppInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/follow-ups/': {
      id: '/_authenticated/app/follow-ups/'
      path: '/follow-ups'
      fullPath: '/app/follow-ups/'
      preLoaderRoute: typeof AuthenticatedAppFollowUpsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/events/': {
      id: '/_authenticated/app/events/'
      path: '/events'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AuthenticatedAppEventsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/customers/': {
      id: '/_authenticated/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AuthenticatedAppCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inventory/new': {
      id: '/_authenticated/app/inventory/new'
      path: '/inventory/new'
      fullPath: '/app/inventory/new'
      preLoaderRoute: typeof AuthenticatedAppInventoryNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inventory/$id': {
      id: '/_authenticated/app/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/app/inventory/$id'
      preLoaderRoute: typeof AuthenticatedAppInventoryIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/events/new': {
      id: '/_authenticated/app/events/new'
      path: '/events/new'
      fullPath: '/app/events/new'
      preLoaderRoute: typeof AuthenticatedAppEventsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/events/$id': {
      id: '/_authenticated/app/events/$id'
      path: '/events/$id'
      fullPath: '/app/events/$id'
      preLoaderRoute: typeof AuthenticatedAppEventsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/customers/new': {
      id: '/_authenticated/app/customers/new'
      path: '/customers/new'
      fullPath: '/app/customers/new'
      preLoaderRoute: typeof AuthenticatedAppCustomersNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/customers/$id': {
      id: '/_authenticated/app/customers/$id'
      path: '/customers/$id'
      fullPath: '/app/customers/$id'
      preLoaderRoute: typeof AuthenticatedAppCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCustomersIdRoute: typeof AuthenticatedAppCustomersIdRoute
  AuthenticatedAppCustomersNewRoute: typeof AuthenticatedAppCustomersNewRoute
  AuthenticatedAppEventsIdRoute: typeof AuthenticatedAppEventsIdRoute
  AuthenticatedAppEventsNewRoute: typeof AuthenticatedAppEventsNewRoute
  AuthenticatedAppInventoryIdRoute: typeof AuthenticatedAppInventoryIdRoute
  AuthenticatedAppInventoryNewRoute: typeof AuthenticatedAppInventoryNewRoute
  AuthenticatedAppCustomersIndexRoute: typeof AuthenticatedAppCustomersIndexRoute
  AuthenticatedAppEventsIndexRoute: typeof AuthenticatedAppEventsIndexRoute
  AuthenticatedAppFollowUpsIndexRoute: typeof AuthenticatedAppFollowUpsIndexRoute
  AuthenticatedAppInventoryIndexRoute: typeof AuthenticatedAppInventoryIndexRoute
  AuthenticatedAppQuotationsIndexRoute: typeof AuthenticatedAppQuotationsIndexRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCustomersIdRoute: AuthenticatedAppCustomersIdRoute,
  AuthenticatedAppCustomersNewRoute: AuthenticatedAppCustomersNewRoute,
  AuthenticatedAppEventsIdRoute: AuthenticatedAppEventsIdRoute,
  AuthenticatedAppEventsNewRoute: AuthenticatedAppEventsNewRoute,
  AuthenticatedAppInventoryIdRoute: AuthenticatedAppInventoryIdRoute,
  AuthenticatedAppInventoryNewRoute: AuthenticatedAppInventoryNewRoute,
  AuthenticatedAppCustomersIndexRoute: AuthenticatedAppCustomersIndexRoute,
  AuthenticatedAppEventsIndexRoute: AuthenticatedAppEventsIndexRoute,
  AuthenticatedAppFollowUpsIndexRoute: AuthenticatedAppFollowUpsIndexRoute,
  AuthenticatedAppInventoryIndexRoute: AuthenticatedAppInventoryIndexRoute,
  AuthenticatedAppQuotationsIndexRoute: AuthenticatedAppQuotationsIndexRoute,
  AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
